### ISSUE TITLE
Error in Chapter 7.2 Make-or-Buy Decisions

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/text_managerial-accounting#2]
The first image (immediately after section heading **Determining Differential Product Costs**) should have a caption/title and also contains an error: "Total annual cost at 2,000 units" should instead read "Total annual cost at 10,000 units".

**Text:**
https://github.com/saylordotorg/text_managerial-accounting/blob/master/s11-02-make-or-buy-decisions.html

**Image:**
https://saylordotorg.github.io/text_managerial-accounting/section_11/e0ec249c37525b1a2ed7cc870bee6535.jpg

**Comment by athuggins** [comment]
This should be fixed.
